### ISSUE TITLE
[bug] Safari on iOS - Cache issue

### ISSUE THREAD

**Issue by lorenzgith** [mickael-kerjean/filestash#229]
### Description of the bug
Safari on iOS gives me the following error message when I try to access the Filestash:
> Error: "FetchEvent.respondWith received an error: TypeError: Headers object's guard is 'immutable'"

It looks like a problem with the cache.

### step by step instructions to reproduce the bug
1.  Open Safari
2.  Go to the Filestash Page
3.  Login
4.  Close the Tab
5.  Go to the Filestash Page again

### Image
![File (1)](https://user-images.githubusercontent.com/58948651/74671663-f763ed00-51ab-11ea-9259-cbb579962aa6.jpg)

**Comment by mickael-kerjean** [comment]
This should have been solved by the previous commit. Can you confirm?

**Comment by Ressort-Informatik** [comment]
I updated it recently and it still doesn't work.
This error also appears when you reload the page twice.

**Comment by mickael-kerjean** [comment]
Did you clear the cache? Also what's the new error message?

**Comment by Ressort-Informatik** [comment]
After clearing the cache is working. But for a permanent solution it is not as soon as I refer to the website twice, the same error message as Lorenzgith has reported. 

In short, the problem persists

**Comment by lorenzgith** [comment]
@mickael-kerjean 
Sorry for the late reply...
With the latest version it seems to work correctly now.
Thanks a lot for fixing it!
